"""add default tables from models file

Revision ID: 4e6830f5903d
Revises: 
Create Date: 2022-11-11 09:16:21.549773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e6830f5903d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_speed', sa.Float(), nullable=False),
    sa.Column('motor_speed', sa.Float(), nullable=False),
    sa.Column('dc_bus_current', sa.Float(), nullable=False),
    sa.Column('soc', sa.Float(), nullable=False),
    sa.Column('battery_cell_voltage_avg', sa.Float(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data')
    op.drop_table('vehicles')
    # ### end Alembic commands ###
